version: 0.0
os: linux
files:
  - source: /
    destination: /webapp/myApp
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/start_server
      timeout: 150
      runas: root
