version: 0.0
os: linux
files:
  - source: /
    destination: /webapp/myApp
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 3600
  ApplicationStart:
    - location: scripts/start_server
      timeout: 3600
  
