#!/bin/sh

cd /webapp/myApp/target
pwd
ls
kill $(ps aux | grep 'ng serve' | grep -v grep | awk '{print $2}')
ng serve --host ec2-3-15-192-185.us-east-2.compute.amazonaws.com  --port 8080 > /dev/null 2> /dev/null < /dev/null &
