#!/bin/sh

cd /webapp/myApp/target
pwd
ls
chmod +rwx file-demo-0.0.1-SNAPSHOT.jar
kill $(ps aux | grep 'file-demo-0.0.1-SNAPSHOT.jar' | grep -v grep | awk '{print $2}')
ng serve --host ec2-3-15-192-185.us-east-2.compute.amazonaws.com  --port 8080r > /dev/null 2> /dev/null < /dev/null &
